/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Bms {
  /**
   * Bms Bundle Spec version
   */
  version: 1;
  /**
   * domain scoped identifier
   */
  id: string;
  /**
   * website
   */
  website_url?: string;
  /**
   * spec url for the group to which this bms belongs
   */
  group_url?: string;
  /**
   * spec url to check for updates on this bms
   */
  updates_url?: string;
  /**
   * resources for this bms
   */
  resources: BmsResource[];
}
export interface BmsResource {
  /**
   * url for the resource
   */
  url: string;
  /**
   * core: the main bundle which includes sound sources. patch: files to be overwritten for modification. additional: additional resources such as new patterns.
   */
  type: "core" | "patch" | "additional";
  /**
   * timestamp in millisec
   */
  updated_at?: number;
  /**
   * short description for the resource
   */
  name?: string;
}
