/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Bms {
  /**
   * Bms Bundle Manifest Spec version
   */
  version: 1;
  /**
   * domain scoped identifier
   */
  id: string;
  /**
   * title
   */
  title: string;
  /**
   * bms manifests which can be treated as the same bms
   */
  aliases?: BmsAlias[];
  /**
   * website
   */
  website_url?: string;
  /**
   * manifest urls for groups to which this bms belongs
   */
  group_manifest_urls?: string[];
  /**
   * manifest url to check for updates on this bms
   */
  updates_manifest_url?: string;
  /**
   * resources for this bms
   */
  resources: BmsResource[];
}
export interface BmsAlias {
  /**
   * domain to which the alias manifest belongs
   */
  domain: string;
  /**
   * domain scoped id of the alias manifest
   */
  id: string;
  [k: string]: unknown;
}
export interface BmsResource {
  /**
   * url for the resource
   */
  url: string;
  /**
   * core: the main bundle which includes sound sources. patch: files to be overwritten for modification. additional: additional resources such as new patterns.
   */
  type: "core" | "patch" | "additional";
  /**
   * timestamp in millisec
   */
  updated_at?: number;
  /**
   * short description for the resource
   */
  name?: string;
}
