/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Group {
  /**
   * Bms Bundle Spec version
   */
  version: 1;
  /**
   * domain scoped identifier
   */
  id: string;
  /**
   * name
   */
  name: string;
  /**
   * website
   */
  website_url?: string;
  /**
   * spec url to check for updates on bmses in this group
   */
  updates_url?: string;
  /**
   * bmses in this group
   */
  bmses?: GroupBms[];
}
export interface GroupBms {
  /**
   * domain scoped identifier
   */
  id: string;
  /**
   * spec url for the bms
   */
  url: string;
}
