/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Group {
  /**
   * Bms Bundle Spec version
   */
  version: 1;
  /**
   * domain scoped identifier
   */
  id: string;
  /**
   * name
   */
  name: string;
  /**
   * group manifests which can be treated as the same group
   */
  aliases?: GroupAlias[];
  /**
   * website
   */
  website_url?: string;
  /**
   * manifest url to check for updates on bmses in this group
   */
  updates_manifest_url?: string;
  /**
   * bmses in this group
   */
  bmses?: GroupBms[];
}
export interface GroupAlias {
  /**
   * domain to which the alias manifest belongs
   */
  domain: string;
  /**
   * domain scoped id of the alias manifest
   */
  id: string;
  [k: string]: unknown;
}
export interface GroupBms {
  /**
   * domain scoped identifier
   */
  id: string;
  /**
   * bmanifest url for the bms
   */
  manifest_url: string;
}
