/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Updates {
  /**
   * Bms Bundle Spec version
   */
  version: 1;
  /**
   * current timestamp in millisec
   */
  timestamp: number;
  /**
   * bmses which have been updated
   */
  bmses?: UpdatesBms[];
}
export interface UpdatesBms {
  /**
   * domain scoped identifier
   */
  id: string;
  /**
   * spec url for the bms
   */
  url: string;
  /**
   * domain scoped identifier for the group
   */
  group_id?: string;
  /**
   * timestamp in millisec
   */
  updated_at?: number;
}
